### ISSUE TITLE
nw.js window instead of Phonegap Desktop

### ISSUE THREAD

**Issue by oliveraustria** [phonegap/phonegap-app-desktop#362]
Hi,

there is a problem with the app for one of my students. She has just got a (chromium) window, however no error or something else. Find attached a screenshot.

Thank you very much,
Oliver

![phonegap_startet_nicht](https://cloud.githubusercontent.com/assets/9258613/7767819/dc9d202c-0075-11e5-9049-452e25cfec84.PNG)

**Comment by hermwong** [comment]
Would you be able to provide the following details to help us troubleshoot the issue:

1. which version of Windows are you running?
1. which version of PhoneGap-Desktop are you running?
1. is there a firewall or antivirus software installed on the computer?
1. are you connected to a corporate network that has a firewall?

**Comment by hermwong** [comment]
possibly related to: https://github.com/phonegap/phonegap-app-desktop/issues/303

**Comment by rafaelkapela** [comment]
Same here...
Windows 7
Last build of PhoneGap Desktop
No firewall or Antivirus
No

**Comment by Mitherek** [comment]
Same issue.
works fine when I install version 0.1.6
Installing version 0.1.7 32x or 64x have the issue.
With version 0.1.6 I get the error 404 /__api__/appzip error so I would like to update in order to get the fix
Windows 7
AV enabled or disabled has no effect
Home network with FW turned of has no effect

**Comment by eleftrik** [comment]
Same issue here. Windows 7 x64, last build.

**Comment by mootieman** [comment]
I've got this error - any news on how to fix this?

**Comment by DevProLog** [comment]
I have the same issue on WIndows 7

**Comment by hermwong** [comment]
Can you guys let me know which OS & architecture:

For example: Windows 7 64 bit and the PG-desktop version that you're using.

I haven't been able to reproduce this issue, so the more data you can provide might allow me to determine what is causing the issue.

**Comment by jadlerassh** [comment]
Windows 10 64-bit
PhoneGap Desktop version 0.1.8

I tried on our firewalled network and on a basic tethered connection and still get the same error.

**Comment by hermwong** [comment]
@jadlerassh, interesting...PhoneGap Desktop Version 0.1.8 is only compiled as a 32 bit exe, I wonder if there might be an issue with it running on a 64 bit Windows computer.

Would you be able to test out a 64 bit version of the PG-Desktop 0.1.8 and report your findings, if I pushed out a version by tomorrow?

**Comment by jadlerassh** [comment]
I'd be happy to test that. 

FYI - I built a 2nd Windows 10 machine and installed the same .exe and it worked properly. I believe everything is configured identically, so I'm not sure why there is a difference.

**Comment by hermwong** [comment]
@jadlerassh that's a bit disconcerting, if there doesn't seem to be a consistent way to reproduce the issue. I'll let you know when I have the 64-bit exe for PhoneGap Desktop 0.1.8 available for testing.

**Comment by hermwong** [comment]
@jadlerassh I've placed the 64-bit Windows version under PhoneGapSetup-win64.exe on the [PhoneGap Desktop 0.1.8 release page](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.1.8) .

**Comment by jadlerassh** [comment]
@hermwong Sorry, but I still get the NW.JS screen on my main Windows 10 PC. The program still works on my backup.

**Comment by mfausten** [comment]
Hi, I have the same problem.

Windows 8.1 Pro x64
Current version of PhoneGap Desktop (0.1.7)
AVG AntiVirus (Doesn't make any difference if disabled)
Yes

PhoneGap 0.1.8 doesn't work for me either. If you need further information, please let me know.

**Comment by TraceyWiedmeyer** [comment]
Same thing on my side, Windows 7
Tried both 32 bit and 64 bit versions, no difference. Made sure install was "unblocked", and added Windows firewall exclusion for the exe.  Running as administrator.

FYI, your 64bit install seems to default to program files(x86) for me.

**Comment by hermwong** [comment]
@TraceyWiedmeyer thanks for pointing out the [Windows 64 bit install issue](https://github.com/phonegap/phonegap-app-desktop/issues/401).

Unfortunately the nwjs issue seems to be something that is happening with the nwjs platform. We've logged an issue with the nwjs project.

**Comment by hermwong** [comment]
Have any of you tried running the app as an administrator?

**Comment by jadlerassh** [comment]
Yes, I ran as an Admin. :)

**Comment by dsbcourtney** [comment]
Any news on this yet as I have the same issue. Windows 7. Security Essentials, Phone Gap 0.1.8

**Comment by hermwong** [comment]
Seems this *might* be related to a [260 character path limit in Windows](http://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows).

reference: https://github.com/nwjs/nw-builder/issues/107#issuecomment-84109909

Could someone try re-installing the `PhoneGap Desktop App` into a directory with a shorter path? For example: `C:\PhoneGap`.

**Comment by andrhahn** [comment]
I just tried it (using 0.1.9 release and Windows7 64-bit) and still get the nw.js window :(

I also tried upgrading to npm3 (https://www.npmjs.com/package/npm-windows-upgrade) which shortens the paths but no luck with that either.

**Comment by davidlyons24** [comment]
Still the same here! 
![phonegap](https://cloud.githubusercontent.com/assets/4345616/9385780/948fc8a0-4758-11e5-86c5-814e46f35546.PNG)

**Comment by davidlyons24** [comment]
And I tryed with a short path and I have the same result!

**Comment by zanattaman** [comment]
Same problem here. Using Windows 7 64bits. Tried all mentioned solutions and none of them work. Any update on that?

**Comment by touchonesolutions** [comment]
Ok, so I have 2 laptops both win7 64bit, one works fine with the desktop app and the other one displays the NW.JS screen as above.

Working laptop:
This has a clean install of v0.1.9 nothing else was installed connected with this app before hand and it works fine.

Non-working laptop:
Now this had the command line version installed via nmp, then desktop version 0.1.8, which didnt work and also 0.1.9 which doesnt work.  I have tried to remove everything but I think something is staying behind.

When I looking my user folder (c:\users\...\AppData\Local) on my working laptop all I see is the PhoneGap directory.  On the non working directory I also get a node-webkit folder, which when I delete comes back when I launch the app.  There are 2 files in there called web data, which get updated when I start the app.  The same files exist in the PhoneGap dir but never get updated.

So is something causing the app to use the wrong directory which means it doesnt start correctly and could it be linked with the earlier installs.

It would be interesting to see everyone else's install history to see if there is a pattern where we have had previous installs of gui or cli that could be causing this issue.

**Comment by jamieyates** [comment]
Has anyone had any luck fixing? I have the same problem on 2 machines. Both Windows 7.

**Comment by zanattaman** [comment]
Are you guys under a Symantec protection system or similar?

**Comment by jamieyates** [comment]
We are using F Secure.
The weird thing is, I changed the location of the file to make the path shorter and it ran fine. When I ran it again (20 mins later) I got the same problem. Its hasn't worked again since.

**Comment by neerajtr2000** [comment]
I have submitted the same issue with id: 439

**Comment by hermwong** [comment]
I've updated my workstation to use Node v4.0 which has some fixes for the long path issue Windows, I'm hoping that it will resolve the issue for some of you. I'll be releasing 0.1.10 Beta within the next few days.

**Comment by hermwong** [comment]
[PhoneGap Desktop 0.1.10 Beta](https://github.com/phonegap/phonegap-app-desktop/releases) has just released. Please update and see if this issue is still happening.

**Comment by eleftrik** [comment]
@hermwong, what about 64 bit version?

Anyway, I tried version 0.1.10 (on Windows 7 64 bit) and I still get the "NW.JS" window.

**Comment by hermwong** [comment]
Looks like we are still running into the long path issue as indicated here: https://github.com/phonegap/phonegap-app-desktop/issues/362#issuecomment-130775883 but not with the PhoneGap Desktop App's install directory; the issue most likely is related to the nesting of dependencies in the node modules used by the PhoneGap Desktop App.

This comment seems to shed more light onto the issue: https://github.com/nodejs/node-v0.x-archive/issues/6960#issuecomment-46704998

**Comment by jamieyates** [comment]
Does this mean windows users cannot use PhoneGap Desktop?

**Comment by hermwong** [comment]
@jamieyates I'm still investigating possible work arounds / solutions to the issue.

**Comment by hermwong** [comment]
It looks like [NPM 3.X](https://github.com/npm/npm/releases/tag/v3.0.0) will have a fix to flatten the nested directories in the node_modules folder to fix the long path issue. 

Currently Node 4 uses NPM 2.14.2.

**Comment by amin2009** [comment]
Same issue here.
 "PhoneGap-Desktop-Beta-0.1.8" wasn't working. It was opens "NW.JS" window. 
Then I installed "PhoneGap-Desktop-Beta-0.1.2-win"
Now, Sometimes PhoneGap runs, Sometimes it opens "Node-Webkit", like https://cloud.githubusercontent.com/assets/801252/6166443/38382f9c-b2a8-11e4-8a5e-f2bd2c0537d2.png
- Path: C:\phonegap\PhoneGap.exe
- My PC: Win-8.1-Pro-64bit / i5 / 8GB RAM 
- Norton Antivirus installed (desable firewall cannot help)

**Comment by hermwong** [comment]
@amin2009, try the latest release 0.1.10 and let me know the results.

I would not advise using older versions of the PhoneGap Desktop App if you plan on pairing with the PhoneGap Developer App. 

Anything older than PhoneGap Desktop App 0.1.7 will not work with PhoneGap Developer App 1.5.2 or newer.

**Comment by amin2009** [comment]
I installed 0.1.10 (installed using installer). It opens PhoneGap.
Then I was testing another copy, extracted zipped version (at path C:\phonegapwin32). Then everything gone. It now opens nw.js window.
I deleted everything and install again, no luck. 
It always takes some time then opens nw.js window.

**Comment by hermwong** [comment]
I've manually updated my npm install to [npm v3.3.4](https://github.com/npm/npm/releases/tag/v3.3.4).

I've built the PhoneGap Desktop locally and it appears that the nested folders within the `node_modules` are flattened.

**Comment by mobedi** [comment]
I have the same problem. Win7 Professional x64.

**Comment by hermwong** [comment]
I just shipped [PhoneGap Desktop 0.1.11](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.1.11). Please try it and let me know if the issue is fixed.

I've tried testing in a Windows 8 VM and Windows 10 VM but haven't had any luck reproducing this issue; I'm guess the VM software does some magic behind the scene that prevents this issue in a VM.

**Comment by touchonesolutions** [comment]
I am running Windows 7 with Norton 360 running.  I uninstalled 0.1.10 and then installed 0.1.11 and have started it several times and it works as it should, no more nw.js window.

Thanks

**Comment by amin2009** [comment]
I installed PhoneGap Desktop 0.1.11. 
Wow, PhoneGap can run now.
Thanks a lot.

**Comment by jamieyates** [comment]
It works!
Thank You hermwong.

**Comment by KingJP** [comment]
After several System Restarts and Tests on the same System where I had the problem, it works for me now!
@amin2009 Can You say what the Problem has been?

**Comment by hermwong** [comment]
@KingJP,

These 2 comments describe the cause of the issue: 
https://github.com/phonegap/phonegap-app-desktop/issues/362#issuecomment-141099008
https://github.com/phonegap/phonegap-app-desktop/issues/362#issuecomment-141167408

**Comment by yolinsoft** [comment]
1
